# Generated by Django 6.0.5 on 2026-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_termsversion_termsacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsversion',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='termsversion',
            name='type',
            field=models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy')], default='terms_of_service', max_length=50),
        ),
    ]
