# Generated by Django 6.0.5 on 2026-07-09 15:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_termsversion_title_termsversion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsversion',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
