# Generated by Django 6.0.5 on 2026-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_termsversion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsacceptance',
            name='version',
            field=models.CharField(default='', max_length=20),
        ),
    ]
