# Generated by Django 6.0.5 on 2026-06-13 11:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_basicpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
