# Generated by Django 6.0.5 on 2026-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
