# Generated by Django 6.0.5 on 2026-06-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPageContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basicpage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('page', 'content_block')},
            },
        ),
        migrations.AddField(
            model_name='basicpage',
            name='content_blocks',
            field=models.ManyToManyField(blank=True, related_name='pages', through='api.BasicPageContentBlock', to='api.contentblock'),
        ),
    ]
