# Generated by Django 6.0.5 on 2026-09-26 10:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_basicpagecontentblock_basicpage_content_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('answer', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='basicpage',
            name='content_faqs',
            field=models.ManyToManyField(blank=True, related_name='pages', to='api.faq'),
        ),
    ]
