# Generated by Django 6.0.5 on 2026-06-25 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('isbn', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('format', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='book.book')),
            ],
            options={
                'unique_together': {('book', 'label')},
            },
        ),
        migrations.CreateModel(
            name='BookTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='book.book')),
            ],
            options={
                'unique_together': {('book', 'topic')},
            },
        ),
    ]
