# Generated by Django 6.0.5 on 2026-07-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='isbn',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
