# Generated by Django 6.0.5 on 2026-07-21 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn13', models.CharField(blank=True, max_length=13)),
                ('isbn10', models.CharField(blank=True, max_length=10)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='book.book')),
            ],
        ),
    ]
