# Generated by Django 6.0.5 on 2026-07-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_edition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='google_volume_id',
            new_name='volume_id',
        ),
    ]
