# Generated by Django 6.0.5 on 2026-07-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_isbn_book_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='isbn',
        ),
    ]
